# Generated by Django 5.2.1 on 2025-07-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_customexam_loadcsv_alter_exammodule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_screen', models.CharField(choices=[('home', 'Home Normal'), ('home2', 'Pantalla Inicio (Antes del examen)'), ('home3', 'Pantalla Resultados')], default='home', max_length=10, verbose_name='Pantalla activa')),
            ],
        ),
    ]
