# Generated by Django 5.2.1 on 2025-07-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_homescreensetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeScreenSetting',
        ),
    ]
