# Generated by Django 5.2.1 on 2025-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_delete_homescreensetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin del examen'),
        ),
        migrations.AddField(
            model_name='stage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio del examen'),
        ),
    ]
