# Generated by Django 5.2.1 on 2025-07-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_stage_active_stage_end_date_stage_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='stage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='start_date',
        ),
    ]
