# Generated by Django 5.2.1 on 2025-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_homescreensetting_delete_screenstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homescreensetting',
            name='active_screen',
        ),
        migrations.AddField(
            model_name='homescreensetting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homescreensetting',
            name='screen_name',
            field=models.CharField(choices=[('home', 'Pantalla de examen'), ('home2', 'Pantalla antes del examen'), ('home3', 'Pantalla después del examen')], default='home', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
