# Generated by Django 5.2.1 on 2025-07-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_homescreensetting_active_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homescreensetting',
            name='display_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del examen'),
        ),
        migrations.AddField(
            model_name='homescreensetting',
            name='display_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del examen'),
        ),
    ]
