# Generated by Django 5.2.1 on 2025-07-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_homescreensetting_display_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['stage'], 'verbose_name': 'etapa', 'verbose_name_plural': 'etapas'},
        ),
    ]
